### ISSUE TITLE
从上游获取 rime-emoji 和 opencc 文件

### ISSUE THREAD

**Issue by amorphobia** [imfuxiao/HamsterInputSchemas#13]
### 提议
我考察后发现，四叶草、星空键道、星猫键道都有复制 opencc 文件，其中有的是方案独有的，有的是可以共用的。

可以共用的有两部分：

1. 从[繪文字](https://github.com/rime/rime-emoji)获取的表情符号转换方案
2. 从 [Open Chinese Convert 開放中文轉換](https://github.com/BYVoid/OpenCC)获取的简繁转换方案

目前，仓的这些文件是从内置方案的仓库中获取这些文件的，然而通常情况这些方案并没有频繁地从上游更新这些转换文件。

**我提议**：让本仓库从各个转换方案的上游获取这些文件，当上游更新的时候，仓可以同样更新。

#### 繪文字
对于 rime-emoji，可以选择从 git 仓库或 release 获取，仓需要选择其一。

由于 rime-emoji 最新版本的词典里只保留了繁体词头，在 GitHub Action 里需要做转换，这一步很简单，在 workflow 里用 `brew install opencc` 安装后简单地命令行转换去重就可以了，我自己已经这样使用了：
https://github.com/amorphobia/rime-user-config/blob/8273af849824d3a641f665f668701cea28b59453/fetch.sh#L80-L81C12

需要选择的是，是否保留繁体格式，这样用户导入的繁体方案也可以使用 rime-emoji 转换。

#### 開放中文轉換
OpenCC 转换文件最简单的获取方式就是从 workflow runner 里复制（上一步安装 opencc 已经含有这些文件），这种方式获取的就是 OpenCC 的 release 版本（[opencc.rb](https://github.com/Homebrew/homebrew-core/blob/master/Formula/opencc.rb)）。

另一种获取方式是拉取 OpenCC 的 git 仓库然后编译。

### 需要做出的选择

- 是否要统一从上游获取
- 繪文字选择 git 仓库还是 release
- 繪文字是否保留繁体词头（目前自带方案使用 emoji 的都是简体词库）
- 開放中文轉換选择 git 仓库编译还是 release 直接复制

我可以来推动这个议题，如果确定好上面的事情后，我来修改代码提交 PR

**Comment by imfuxiao** [comment]
emoji的的那部分我明白了，目前这部分目前都是各方案自己内置的，改为从[繪文字](https://github.com/rime/rime-emoji)拉取最新的。

opencc这部分我不是太明白您的描述和这部分所描述的需求。目前opencc的文件，主要是从 librime 的 release deps包中复制的，个别方案如果有自己的opencc文件，才需要复制到公共文件目录中。

**Comment by amorphobia** [comment]
@imfuxiao 我提议的时候没注意到 librime 自带简繁转换的词库并最终会覆盖方案的这些文件，这种情况下，则不需要对这部分进行拉取了。抱歉我没有考察清楚。

> 改为从[繪文字](https://github.com/rime/rime-emoji)拉取最新的

请问最新是 git master 最新还是最新 release？

另外一个问题就是，emoji 是否要保留繁体？

**Comment by imfuxiao** [comment]
您太客气了，只是讨论下。

这个项目 main 分支就是最新的。

是否保留繁体的问题，我不太懂，我理解emoji是表情，为啥有简繁的区分……

**Comment by amorphobia** [comment]
> 为啥有简繁的区分

是这样的，rime-emoji 是用 opencc 技术实现的中文字词到 emoji 表情的转换，这里的「简繁」说的是转换前的中文字词，如果 emoji 词典里只保留简体，那么内置方案体积会小一点，但就只能对本身就是简体的方案（如四叶草、键道）起作用，假如用户自己导入繁体方案，繁体字词就不能被转换成 emoji 表情

**Comment by amorphobia** [comment]
> 这个项目 main 分支就是最新的

好像是我没问清楚，我们在获取 rime-emoji 的时候，是从 rime-emoji 的 [release](https://github.com/rime/rime-emoji/releases/latest) 下载，还是 git clone 获取它的仓库 master 版？

**Comment by imfuxiao** [comment]
总算明白了，就是比如打哈哈的时候，候选字会出来哈哈的emoji，所以有对应的简繁。

我觉得应该用release版本。

**Comment by imfuxiao** [comment]
建议简繁都支持。

**Comment by amorphobia** [comment]
> 我觉得应该用release版本
> 建议简繁都支持

好嘞
