### ISSUE TITLE
申請加入福州話羅馬字

### ISSUE THREAD

**Issue by Guanchishan** [imfuxiao/HamsterInputSchemas#23]
GitHub repo: https://github.com/ZySieng/Lo-ma-ci/tree/master

這是一款有著逾百年歷史的書寫系統，中國第一份兒童刊物《小孩月報》就是用這種書寫系統寫就的。

閩東語維基百科使用這門書寫系統：https://cdo.wikipedia.org/wiki/Tàu_Hiĕk

維基百科對這門書寫系統的介紹：https://zh.wikipedia.org/zh-hant/平話字

**Comment by imfuxiao** [comment]
您好，我已将此方案上传至「仓输入法」云端，您可以在「输入方案设置」-> 右上 + -> 方案下载，

方案列表中有：「福州話教會羅馬字RIME輸入方案」

如您需要自行上传，可将您的 apple 账号邮件发我，我会邀请您进入一个上传方案的测试列表。
